spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        name: ${DB_NAME}

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true